### PR TITLE
unicorn commands are use 'sudo' if Debian?

### PR DESCRIPTION
**Pull request by hiphapis**
issues #8 #31 #53 
already have a PR #37 

but this version is upgraded. point is detect 'Debian' and then use `sudo`

TESTED
- local: Macbook
- remote: Debian

TODO: 
- test with other linux
- enhance 'detect Debian' regexp

### CODE REVIEW

**Comment by vforvova** [comment]
:+1:

**Comment by hiphapis** [comment]
@vforvova Thanks for your vote ;)
i inspired your pull request. Thanks :)

**Comment by vforvova** [comment]
@hiphapis thank **you**! I will use your fork since now! ;)

**Comment by wynksaiddestroy** [comment]
Any chance on getting @hiphapis pull request merged? At the moment this plugin simply doesn't work with debian jessie.

**Comment by wynksaiddestroy** [comment]
@hiphapis Have you tried your patch on a recent version of debian jessie? If I'm executing `uname -a` on my machine, it will return `Linux lvps91…de 3.16.0-042stab108.7 #1 SMP Wed Jul 15 15:49:08 MSK 2015 x86_64 GNU/Linux` and won't match your regular expression.

**Comment by rhomeister** [comment]
Closing. Already merged https://github.com/capistrano-plugins/capistrano-unicorn-nginx/pull/55

**Pull request closed without merging**
