### PR TITLE
Call service with sudo

### PR DESCRIPTION
**Pull request by vforvova**
Hi, @bruno- ! I'm not as competent in deployment as I want to be and this fix may not work in some cases, but I can't use service without sudo or unicorn_initd_file function calling. I will be glad if you would help me to make this commit better. 
This pull request can also may be related to issues #8 and #31.

### CODE REVIEW

**Comment by Salet** [comment]
Hi @bruno- 
Don't want to rush you, but is there any chance this gets merged soon? That would fasten up deploys a little for me :)

**Comment by ZJvandeWeg** [comment]
+1. Solved my issue; thanks.

**Comment by vforvova** [comment]
Look pr #66 . Please close this pr because of it.

**Comment by thomas88** [comment]
This was also necessary for me on Debian Jessie, as `service` is only available to root there.

Duplicate PRs: #55, #60, #66, #73
Related issues: #53

@bruno- / @rhomeister

**Pull request closed without merging**
